swagger: '2.0'
info:
  title: OpenAPI definition
  version: v0
schemes:
  - https
basePath: /
paths:
  /v1/certificate/citizen/io:
    post:
      consumes:
        - application/json
      description: >-
        Servizio che restituisce un certificato a partire da AutCode e CF del
        cittadino.
      operationId: getCertificateByAutAndCF
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CertificateByAutAndCFRB'
      produces:
        - application/json
      responses:
        '200':
          description: Certificato trovato
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
      summary: Restituisce certificato
      tags:
        - Servizio dei Cittadini
  /v1/certificate/citizen/io/refresh:
    post:
      consumes:
        - application/json
      description: Servizio per comunicare un nuovo codice fiscale.
      operationId: managePreviousCertificates
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CertificateByCFRB'
      produces:
        - application/json
      responses:
        '200':
          description: Comunicazione avvenuta
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
      summary: Comunica un nuovo codice fiscale
      tags:
        - Servizio dei Cittadini
definitions:
  CertificateByAutAndCFRB:
    properties:
      authCodeSHA256:
        description: Authorization token
        type: string
      cfSHA256:
        description: Codice fiscale
        type: string
    type: object
  CertificateByCFRB:
    properties:
      cfSHA256:
        description: Codice fiscale errato
        type: string
    type: object
  ErrorResponseDTO:
    properties:
      code:
        description: Codice di errore
        format: int32
        type: integer
      message:
        description: Messaggio di errore
        type: string
    type: object
  PreviousCertificateResponseDTO:
    properties:
      data:
        format: int32
        type: integer
      error:
        $ref: '#/definitions/ErrorResponseDTO'
      keyDuplicate:
        type: string
      spanID:
        type: string
      traceID:
        type: string
    type: object
  QrCodeInfoDTO:
    properties:
      qrcodeB64:
        description: Content del qrcode espresso in Base64
        type: string
      uvci:
        description: UVCI
        type: string
      fglTipoDgc:
          type: string
          description: Indica il tipo di dgc
    type: object
  SearchSingleQrCodeResponseDTO:
    properties:
      data:
        $ref: '#/definitions/QrCodeInfoDTO'
      error:
        $ref: '#/definitions/ErrorResponseDTO'
      keyDuplicate:
        type: string
      spanID:
        type: string
      traceID:
        type: string
    type: object