import { AzureFunction } from "@azure/functions";
import { getFetch } from "@pagopa/ts-commons/lib/agent";
import { createClient } from "../generated/dgc/client";
import { getConfigOrThrow } from "../utils/config";
import { NotifyNewProfile } from "./handler";

const config = getConfigOrThrow();

// TODO: Check if we can use autogenerated client or we need a custom fetch
const client = createClient({
  baseUrl: config.DGC_BASE_URL.href,
  fetchApi: getFetch(process.env)
});

const index: AzureFunction = NotifyNewProfile(client);

export default index;
